apiVersion: v1
kind: Service
metadata:
  name: visualization-ui
  namespace: kalmar-digital-twin
  labels:
    app: visualization-ui
    tier: frontend
    project: kalmar-digital-twin
spec:
  type: ClusterIP
  selector:
    app: visualization-ui
    tier: frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
