image: alpine:3.19

stages:
  - deploy

deploy:
  stage: deploy
  before_script:
    - apk add --no-cache openssh-client rsync bash
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H "$VM_HOST" >> ~/.ssh/known_hosts
  script:
    - rsync -az k8s scripts "$VM_USER@$VM_HOST:/home/$VM_USER/infrastructure-k8s/"
    - ssh "$VM_USER@$VM_HOST" "sudo k3s kubectl apply -f /home/$VM_USER/infrastructure-k8s/k8s/namespaces/namespace-kalmar-digital-twin.yaml"
    - ssh "$VM_USER@$VM_HOST" "sudo k3s kubectl apply -f /home/$VM_USER/infrastructure-k8s/k8s/config/ --recursive"
    - ssh "$VM_USER@$VM_HOST" "sudo k3s kubectl apply -f /home/$VM_USER/infrastructure-k8s/k8s/infra/ --recursive"
    - ssh "$VM_USER@$VM_HOST" "sudo k3s kubectl apply -f /home/$VM_USER/infrastructure-k8s/k8s/apps/ --recursive"
    - ssh "$VM_USER@$VM_HOST" "sudo k3s kubectl apply -f /home/$VM_USER/infrastructure-k8s/k8s/ingress/ingress.yaml"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
